name: exam_5month
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  firebase_database: ^11.3.8
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  firebase_auth: ^5.6.2
  shared_preferences: ^2.5.3
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
